name: Scrape Badi

on:
  push:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  build-run-and-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t badi-scraper-image .

    - name: Run Docker container
      run: |
        docker run --rm -v ${{ github.workspace }}/:/app/ --name badi-scraper-container badi-scraper-image
    - name: Commit and push data
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'main'
        commit-message: 'Update data'
        force-add: 'true'
        files: swimmers.csv swimmers.png
        name: GitHub Actions
        email: actions@github.com